### ISSUE TITLE
Change Accent Color

### ISSUE THREAD

**Issue by Nightshade935** [CapnKitten/Spotify-Discord#17]
I really love this theme and have been using it since it came out but is there anyway you can change the accent color? I like the green but I also want to experiment with other colors.

**Comment by CapnKitten** [comment]
```css
:root {
	--accent-color: #1db954;
	--accent-hover: #1ed760;
	--accent-rgb: 29,185,84;
	--accent-text-color: #fff;
}
```
Sorry for the massive delay, just add those to your custom css or theme file directly and change the values.
