### ISSUE TITLE
Add USRBG Support

### ISSUE THREAD

**Issue by dav1312** [CapnKitten/Spotify-Discord#19]
USRBG - https://github.com/Discord-Custom-Covers/usrbg

![image](https://user-images.githubusercontent.com/63931154/115242916-a12d6980-a122-11eb-9c44-22be4a073d64.png)
![image](https://user-images.githubusercontent.com/63931154/115242975-b1dddf80-a122-11eb-867e-2429117fc762.png)

```css
/* Default USRBG position */
.userPopout-3XzG_A {--user-popout-position: center}

/* USRBG User Popout */
.userPopout-3XzG_A {transform:translateZ(0)}
#app-mount .userPopout-3XzG_A .wrapper-3t9DeA::after {
	content: '';
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	z-index: -1;
	pointer-events: none;
	opacity: .5;
	background-size: cover;
	background-repeat: no-repeat;
	background-position: var(--user-popout-position) center;
	background-image: var(--user-background);
}
.userPopout-3XzG_A .header-2BwW8b,
.userPopout-3XzG_A .rolesList-22qj2L,
.userPopout-3XzG_A .footer-1fjuF6 {
	z-index: 1;
}

/* USRBG Profile Modal */
.root-SR8cQa .topSectionNormal-2-vo2m,
.root-SR8cQa .topSectionPlaying-1J5E4n,
.root-SR8cQa .topSectionSpotify-1lI0-P,
.root-SR8cQa .topSectionStreaming-1Tpf5X,
.root-SR8cQa .topSectionXbox-3fWLjS {transform: translateZ(0)}
#app-mount .header-QKLPzZ .wrapper-3t9DeA::before {
	content: '' !important;
	position: fixed;
	top: 0;
	left: 0;
	width: 100%;
	height: 100%;
	opacity: .5;
	pointer-events: none;
	background: var(--user-background) center/cover no-repeat;
}
.root-SR8cQa .headerInfo-30uryT,
.root-SR8cQa .tabBarItem-1b8RUP,
.root-SR8cQa .activity-1ythUs {
	z-index: 1;
	position: relative;
}
```
