### ISSUE TITLE
Displeased with color changes.

### ISSUE THREAD

**Issue by OiGamerLads** [CapnKitten/Spotify-Discord#23]
Hello! I would like a previous version of the Spotify discord available, as I do not like the new ones very much. If this is possible, then please do it. If not, I'm sorry!

**Comment by CapnKitten** [comment]
The color changes reflect the Spotify UI changes that recently happened. However, you can customize it with relative ease to make it look similar to how it used to look. Take the code below and paste it either into your custom css (located in your user settings) or in the theme file itself.
```css
:root {
	--chat-color: #1e1e1e;
	--sidebar-color: #191919;
	--sidebar-panel: #242424;
	--title-bar: #191919;

	--bar-color: #2c2c2c;
	--bar-border-color: #2c2c2c;

	--card-color: rgba(255,255,255,0.05);

	--button-background: rgba(0,0,0,0.3);
}

.channelTextArea-rNsIhG,
.channelTextArea-1LDbYG {
	margin: 13px 0;
}
```
